db.libros.insertMany([
    {libro:"El nombre del viento",genero:"fantasia",puntuacion:8},
    {libro:"El temor de un hombre sabio",genero:"fantasia",puntuacion:10},
    {libro:"Las puertas de piedra",genero:"fantasia",puntuacion:3},
    {libro:"El imperio final",genero:"drama",puntuacion:7},
    {libro:"El pozo de la ascension",genero:"drama",puntuacion:8},
    {libro:"El quinto mandamiento",genero:"historia",puntuacion:7},
    {libro:"La marca del guerrero",genero:"fantasia",puntuacion:6},
    {libro:"La taberna errante",genero:"humor",puntuacion:9},
    {libro:"El koala asesino",genero:"humor",puntuacion:4},
    {libro:"La peste negra",genero:"historia",puntuacion:4},
    {libro:"Harry Potter y la piedra filosofal",genero:"fantasia",puntuacion:1},
    {libro:"Un monstruo viene a verme",genero:"drama",puntuacion:9},
    {libro:"Cancion de hielo y fuego",genero:"fantasia",puntuacion:9},
    {libro:"Caballo de troya",genero:"historia",puntuacion:7},
    {libro:"Mi familia y otros animales",genero:"humor",puntuacion:7},
    {libro:"El camino de los reyes",genero:"drama",puntuacion:8},
    {libro:"Una chica en la nieve",genero:"drama",puntuacion:6},
    {libro:"Symarillion",genero:"fantasia",puntuacion:6.5},
    {libro:"2000 chistes para todos",genero:"humor",puntuacion:2.5},
    {libro:"Timantti",genero:"humor",puntuacion:4.5},
])